exec wl-paste -t text --watch clipman store

exec swayidle -w \
  timeout 1200 'swaylock -f -c 000000' \
  timeout 1201 'swaymsg "output * dpms off"' \
	    resume 'swaymsg "output * dpms on"' \
  before-sleep 'swaylock -f -c 000000' \

# exec fcitx5
exec_always fcitx5 -d
exec_always export GTK_IM_MODULE=fcitx5
exec_always export QT_IM_MODULE=fcitx5
exec_always export XMODIFIERS=@im=fcitx5

exec mako
exec /usr/share/sway/scripts/inactive-windows-transparency.py --opacity 0.8
exec nm-applet --indicator
